/**
 * The database: what may be lost without a key release depending on it -
 * requests and their history, leases, and the log of key fetches.
 * PostgreSQL or CockroachDB; everything here is written to work on both.
 *
 * The tables are created at start-up rather than by migrations, so the agent
 * stays one binary. A change to them later is a decision for then.
 */
#ifndef WX_DB_H
#define WX_DB_H

#include "util.h"

#include <meta_pg.h>
#include <meta_sql.h>

static const char *const dbSchema[] = {
  "CREATE TABLE IF NOT EXISTS requests ("
  " id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
  " created TIMESTAMPTZ NOT NULL DEFAULT now(),"
  " type TEXT NOT NULL,"
  " payload JSONB NOT NULL,"
  " status TEXT NOT NULL,"
  " reason TEXT NOT NULL DEFAULT '',"
  " checks JSONB NOT NULL DEFAULT '[]',"
  " decided TIMESTAMPTZ,"
  " decided_by TEXT NOT NULL DEFAULT '')",

  "CREATE INDEX IF NOT EXISTS requests_open ON requests (status, id)",

  "CREATE TABLE IF NOT EXISTS leases ("
  " disk_id TEXT PRIMARY KEY,"
  " report_id TEXT NOT NULL,"
  " chip_id TEXT NOT NULL,"
  " expires TIMESTAMPTZ NOT NULL,"
  " first_seen TIMESTAMPTZ NOT NULL)",

  "CREATE TABLE IF NOT EXISTS releases ("
  " id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
  " ts TIMESTAMPTZ NOT NULL DEFAULT now(),"
  " disk_id TEXT NOT NULL DEFAULT '',"
  " step TEXT NOT NULL,"
  " ok BOOL NOT NULL,"
  " detail TEXT NOT NULL DEFAULT '',"
  " ctx JSONB NOT NULL DEFAULT '{}',"
  " source TEXT NOT NULL DEFAULT '')",

  "CREATE INDEX IF NOT EXISTS releases_disk ON releases (disk_id, id)",
};

static const char *dbUrl(void) {
  return env("WX_DB", "postgresql://root@127.0.0.1:26257/keyagent?sslmode=disable");
}

/** Creates what is missing. Run once, before any worker serves. */
static int dbPrepare(void) {

  PGconn *db = meta_pgOpen(dbUrl());

  if (db == NULL) {
    fprintf(stderr, "wx-keyagent: cannot reach the database\n");
    return 1;
  }

  for (size_t i = 0; i < sizeof dbSchema / sizeof dbSchema[0]; ++i) {

    PGresult *r = db.query(dbSchema[i]);

    if (r == NULL || PQresultStatus(r) != PGRES_COMMAND_OK) {
      fprintf(stderr, "wx-keyagent: schema: %s\n", db.lastError());
      db.close();
      return 1;
    }
  }

  db.close();

  return 0;
}

/**
 * One connection per worker, and one query on it at a time.
 *
 * Tasks of one worker interleave wherever one of them waits, and a libpq
 * connection takes one statement at a time - a second task sending while the
 * first waits for its answer gets "another command is already in progress",
 * or worse, the first one's rows. The channel holds a single token: whoever
 * has it may use the connection.
 */
typedef @chan(int, 1) dbTurn_t;

static PGconn *database;
static dbTurn_t dbTurn;

static int dbConnect(void) {

  database = meta_pgOpen(dbUrl());

  if (database == NULL) {
    fprintf(stderr, "wx-keyagent: this worker cannot reach the database\n");
    return 1;
  }

  dbTurn.send(1);

  return 0;
}

/** A statement with its values beside it. The caller clears the result. */
META_OWNS static PGresult *dbAsk(const sql_t *query) {

  int token;
  PGresult *r;

  if (database == NULL || !dbTurn.receive(&token))
    return NULL;

  r = database.ask(query);

  /* a broken connection is opened again for the next one */
  if (r == NULL && PQstatus(database) != CONNECTION_OK)
    PQreset(database);

  dbTurn.send(token);

  return r;
}

/** True when a statement that returns no rows went through. */
static bool dbDo(const sql_t *query) {

  PGresult *r = dbAsk(query);
  bool done = r != NULL && PQresultStatus(r) == PGRES_COMMAND_OK;

  if (r != NULL)
    PQclear(r);

  return done;
}

#endif /* WX_DB_H */
